### ISSUE TITLE
Add Integration Error: This integration does not support configuration via the UI.

### ISSUE THREAD

**Issue by mattwells** [vwt12eh8/hassio-ecoflow#10]
I am fairly sure that this is a me issue as I have only just installed Home Assistant for the first time but when I click the "My Add Integration" button at the bottom of the readme I get this error when I click through to my Home Assistant instance:

> This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

Please could you advise? HA noob /

Home Assistant 2022.7.4 
Supervisor 2022.07.0 
Operating System 8.2 
Frontend 20220707.0 - latest

**Comment by klaus1956** [comment]
I had the same problem - if you install the github-link in HACS it wors smoothly

**Comment by mattwells** [comment]
Hi Klaus, nothing is coming up when I search for github-link do you mean this one? https://www.home-assistant.io/integrations/github/

**Comment by klaus1956** [comment]
Hi Matt - I put the integration link https://github.com/vwt12eh8/hassio-ecoflow  in HACS/Integrations/user defined repositories (the  3 dots top right) - after HA restart the EcoFlow was found automaticly as a new integration (as far as I remember)

**Comment by mattwells** [comment]
Okay, I came acros HACS multiple times and have now looked up what it actually is and installed it, I believe correctly. I have no added this repository to HACS and I can now see a card for EcoFlow. Clicking on the card I get a screen that says "The developer has not provided any more information for this repository". There doesn't appear to be any configuration in the UI and Home Assistant OS doesn't appear to have Python installed as a command to start running the scripts from the CLI. Could you advise what I should do next please?

**Comment by klaus1956** [comment]
If I remember right I just imported it to HACS and after the next start of HA it appears under configuration/integrations

**Comment by mattwells** [comment]
FINALLY GOT IT! xD thank you for your assistance Klaus, I was really struggling there without your help :)

**Comment by vwt12eh8** [comment]
Now that I think about it, I'm considering removing the "ADD INTEGRATION" button at the end of the README as it is confusing to hassio newbies.

**Comment by klaus1956** [comment]
I agree 👍
Can you insert a section that it has to be integrated by HACS please.
