### ISSUE TITLE
Check Delta Max As Working

### ISSUE THREAD

**Issue by DevTodd** [vwt12eh8/hassio-ecoflow#12]
First of all - Thank you!

Second - Works flawlessly with a Delta Max so feel free to add a check mark next to that as working:

![image](https://user-images.githubusercontent.com/32474971/179373487-b00700a4-8cef-47f7-b296-c73b23098484.png)

**Comment by vwt12eh8** [comment]
Thanks for your help with the test.

Just to make sure, did you find any entities with incorrect units? (For example, the value needs to be 1/10, etc.) 
Please check with particular care for entities in the diagnostic category.

**Comment by DevTodd** [comment]
Everything looked good to me, but here you go to see for yourself:

![image](https://user-images.githubusercontent.com/32474971/179381287-706b5e7a-5b23-4be7-b1da-be0ffdfa6141.png)

**Comment by vwt12eh8** [comment]
You'll probably be fine.

I will mark it as tested.
