### ISSUE TITLE
Delta Pro - Discharge/Charge Level

### ISSUE THREAD

**Issue by Roughman007** [vwt12eh8/hassio-ecoflow#13]
This is not an issue but rather a **request**:

Hi, would it be possible to add a "Discharge/Charge Level" function like in the app? To set the battery limit.

Thanks.

**Comment by vwt12eh8** [comment]
That functionality is already implemented.

If this is not available, can you provide diagnostic information?

**Comment by Roughman007** [comment]
Sorry, here is diagnostic information:

> {
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.7.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Prague",
    "os_name": "Linux",
    "os_version": "5.15.45",
    "supervisor": "2022.07.0",
    "host_os": "Home Assistant OS 8.2",
    "docker_version": "20.10.14",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "ecoflow": {
      "version": "2.0",
      "requirements": [
        "reactivex"
      ]
    },
    "hacs": {
      "version": "1.26.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "dahua": {
      "version": "0.5.0",
      "requirements": []
    },
    "frigate": {
      "version": "2.3",
      "requirements": []
    },
    "ui_lovelace_minimalist": {
      "version": "v1.0.2",
      "requirements": []
    },
    "opnsense": {
      "version": "0.1.0",
      "requirements": [
        "mac-vendor-lookup>=0.1.11"
      ]
    },
    "spacex": {
      "version": "029",
      "requirements": [
        "spacexpypi==0.0.12"
      ]
    }
  },
  "integration_manifest": {
    "domain": "ecoflow",
    "name": "Ecoflow",
    "version": "2.0",
    "documentation": "https://github.com/vwt12eh8/hassio-ecoflow",
    "issue_tracker": "https://github.com/vwt12eh8/hassio-ecoflow/issues",
    "requirements": [
      "reactivex"
    ],
    "config_flow": true,
    "codeowners": [
      "@vwt12eh8"
    ],
    "dhcp": [
      {
        "hostname": "ecoflow_*",
        "macaddress": "*"
      }
    ],
    "iot_class": "local_push",
    "is_built_in": false
  },
  "data": {
    "mppt": {
      "dc_in_fault": 0,
      "dc_in_version": "3.1.0.21",
      "dc_in_voltage": 96.0,
      "dc_in_current": 1248,
      "dc_in_power": 12080,
      "_volt_?_out": 490,
      "_curr_?_out": 2300,
      "_watts_?_out": 11294,
      "dc_in_temp": 65,
      "dc_in_type": 2,
      "dc_in_type_config": 0,
      "_dc_in_type": 2,
      "dc_in_state": 1,
      "anderson_out_voltage": 0,
      "anderson_out_current": 0,
      "anderson_out_power": 0,
      "car_out_voltage": 0,
      "car_out_current": 0,
      "car_out_power": 0,
      "car_out_temp": 0,
      "car_out_state": 0,
      "dc24_temp": 28,
      "dc24_state": 1,
      "dc_in_pause": 0,
      "_dc_in_switch": 64,
      "_dc_in_limit_max": 31,
      "_dc_in_limit_custom": 0
    },
    "pd": {
      "model": 1,
      "pd_error": 0,
      "pd_version": "1.0.0.59",
      "wifi_version": "0.0.3.6",
      "wifi_autorecovery": 0,
      "battery_level": 44,
      "out_power": 782,
      "in_power": 1203,
      "remain_display": 31320.0,
      "beep": 0,
      "_watts_anderson_out": 1,
      "usb_out1_power": 0,
      "usb_out2_power": 0,
      "usbqc_out1_power": 0,
      "usbqc_out2_power": 0,
      "typec_out1_power": 0,
      "typec_out2_power": 13,
      "typec_out1_temp": 28,
      "typec_out2_temp": 32,
      "car_out_state": 0,
      "car_out_power": 0,
      "car_out_temp": 0,
      "standby_timeout": 3600.0,
      "lcd_timeout": 1800.0,
      "lcd_brightness": 141,
      "car_in_energy": 6,
      "mppt_in_energy": 355647,
      "ac_in_energy": 18728,
      "car_out_energy": 536,
      "ac_out_energy": 239238,
      "usb_time": 51828.0,
      "typec_time": 37413.0,
      "car_out_time": 6491.0,
      "ac_out_time": 6106.0,
      "ac_in_time": 3764615.0,
      "car_in_time": 239.0,
      "mppt_time": 2996787.0,
      "_ext_rj45": 0,
      "_ext_infinity": 0
    },
    "inverter": {
      "ac_error": 0,
      "ac_version": "2.1.1.76",
      "ac_in_type": 0,
      "ac_in_power": 0,
      "ac_out_power": 769,
      "ac_type": 8,
      "ac_out_voltage": 230031,
      "ac_out": 4118,
      "ac_out_freq": 50,
      "ac_in_voltage": 0,
      "ac_in_current": 0,
      "ac_in_freq": 0,
      "ac_out_temp": 32,
      "dc_in_voltage": 0,
      "dc_in_current": 0,
      "dc_in_temp": 32,
      "fan_state": 3,
      "ac_out_state": 1,
      "ac_out_xboost": 0,
      "ac_out_voltage_config": 230000,
      "ac_out_freq_config": 1,
      "fan_config": 0,
      "ac_in_pause": 0,
      "ac_in_limit_switch": 2,
      "ac_in_limit_max": 0,
      "ac_in_limit_custom": 200
    },
    "ems": {
      "_state_charge": 1,
      "_chg_cmd": 1,
      "_dsg_cmd": 1,
      "battery_main_voltage": 50984,
      "battery_main_current": 130000,
      "_fan_level": 0,
      "battery_level_max": 91,
      "model": 1,
      "battery_main_level": 44,
      "_flag_open_ups": 1,
      "battery_main_warning": 0,
      "battery_remain_charge": 31320.0,
      "battery_remain_discharge": 8639940.0,
      "battery_main_normal": 1,
      "battery_main_level_f32": 43.88500213623047,
      "_is_connect": 3,
      "_max_available_num": 1,
      "_open_bms_idx": 1,
      "battery_main_voltage_min": 49420,
      "battery_main_voltage_max": 50020,
      "battery_level_min": 9,
      "generator_level_start": 0,
      "generator_level_stop": 100
    }
  }
}

**Comment by Roughman007** [comment]
I just figured it out. Just updated the extension to 2.1.1 everything works as it should. I'll close this thread.

[https://imgur.com/a/0UdaunY](https://imgur.com/a/0UdaunY)

Thanks.
