### ISSUE TITLE
Delta Pro - Firmware question

### ISSUE THREAD

**Issue by Roughman007** [vwt12eh8/hassio-ecoflow#16]
Hi, this is not an issue but rather a question:

I have Delta Pro(firmware 0.3.6), has anyone tried updating to the latest(0.4.8) firmware? Will this integration still work for me? Has anyone tried this?

Thanks.

**Comment by GCustom** [comment]
I'm running this version on my units it seems to work fine for them

**Comment by Roughman007** [comment]
I just updated to the latest firmware, everything works Thanks.

**Comment by golden-guy** [comment]
Has anybody already installed firmware version 1.0.0.96 on the Delta Pro, and if so, does the ecoflow integration still fully work?

**Comment by JasonMM2000** [comment]
Yes, I do. All is working.

**Comment by golden-guy** [comment]
Ok fine, thanks for your quick feedback!
