### ISSUE TITLE
Delta Pro: Charging condition displayed wrong

### ISSUE THREAD

**Issue by golden-guy** [vwt12eh8/hassio-ecoflow#23]
Hello! First of all thanks alot for your work, you really did an awesome job with this integration! In fact I installed HA only because of this.
I recently got a Delta Pro and I'm just about to finish the HA setup, using the latest HA version (2022.7.7) and hassio-ecoflow version 2.2.1

I noticed an issue that the Charging sensor says "Not charging" while the Delta Pro was running on AC with battery level at 50% and the AC output turned on. Actually it always says "Not charging", regardless of charging or not (bypass mode).
I can confirm the battery is indeed charging, with the battery level gradually increasing. Every related readout looks good, apart from the charging indicator.

Attaching debug output for your reference. Just let me know if you need more infos

[config_entry-ecoflow-b59e0ccb379fad5eff3c3280bd845a54.json.txt](https://github.com/vwt12eh8/hassio-ecoflow/files/9232655/config_entry-ecoflow-b59e0ccb379fad5eff3c3280bd845a54.json.txt)
.

**Comment by vwt12eh8** [comment]
Sorry. There was a fatal bug and we have fixed it.

**Comment by golden-guy** [comment]
Using this hotfix the charging condition is now reported fine when charging. Will check the other scenarios as well later when the battery is fully charged (bypass mode) as well as with AC input off.

**Comment by Jiriteach** [comment]
Can confirm that its reporting as expected in bypass mode. My batteries are charged in bypass and its showing as not charging.

**Comment by golden-guy** [comment]
Indeed. Once the unit is fully charged and switches to bypass mode, the charging indicator correctly reads "Not charging". The readout is also correct when "AC charge" has been switched off.
