### ISSUE TITLE
Delta Pro: AC input sensors' data wrong in pass-through mode

### ISSUE THREAD

**Issue by golden-guy** [vwt12eh8/hassio-ecoflow#25]
I noticed another issue with the AC input sensors' readout in bypass (pass-through) mode on my Delta Pro running hassio-ecoflow 2.2.2):
Once the battery is fully charged, and the unit switches to pass-through mode, the sensor values for AC are "Off" resp. "0 W", although the unit is still plugged on AC and passing on power to the active AC output. The AC output power is correctly displayed, as well as the "Total input" and "Total output".

As a side note: According to the activity log, the AC input was reset at the same time the Charging indicator changed to "Not charging" when the battery was full. The ac_in_power in the debug log looks correct in this case (and is aligned with the ac_out_power)

[config_entry-ecoflow-b59e0ccb379fad5eff3c3280bd845a54_2.json.txt](https://github.com/vwt12eh8/hassio-ecoflow/files/9235053/config_entry-ecoflow-b59e0ccb379fad5eff3c3280bd845a54_2.json.txt)

**Comment by golden-guy** [comment]
On the Delta Pro it stays constantly off once the device goes into pass-through mode (I did not update the firmeware yet though) When I compared the three debug files I took today the culprit seems to be the ac_in_type: Once charging has finished, the "ac_in_type" reads "0" which is the same as when the unit is unplugged from AC, even though AC input (ac_in_power) has a positive value.

**Comment by vwt12eh8** [comment]
I have previously addressed this in the RIVER series so that you can have input entities in AC and DC respectively.

However, that did not work well and even caused problems with DELTA.

We are going to revert this and remove the AC/DC input entities from the RIVER series, leaving only the total input entities (the DELTA series will continue to have AC/DC input entities).

**Comment by Jiriteach** [comment]
> 

That should work - while there would be valid use cases for input on AC and DC - seems that this is problematic so total is still fine as that will still detect no input.

**Comment by golden-guy** [comment]
@vwt12eh8 The AC Input still reads "off" using the 2.2.3 code when in bypass-mode and active AC power draw.

**Comment by vwt12eh8** [comment]
@golden-guy It seems to be a firmware spec that reports no input when charged to max. This was also the case with DC input.

I would not recommend using this entity to determine if there is a real input or not.

As an alternative, it would be more reliable to determine that there is an input if the AC input voltage is of a certain value (e.g. 10V or higher).

**Comment by golden-guy** [comment]
Alright, that's fine. I will just use another entity then, as you have suggested. Thanks for your always great support!
