### ISSUE TITLE
Energy Dashboard - Register Battery

### ISSUE THREAD

**Issue by mweber89** [vwt12eh8/hassio-ecoflow#48]
At first, many thanks for building this integration. The registration of new devices worked like a charm.

When using the River Max as UPS or mainly as pass-through battery, the following configuration is incorrect:

total input energy : Home Battery Storage -> Energy going in to the battery
total output energy : Home Battery Storage -> Energy coming out of the battery

It would add the input and output (that is equal if the battery is fully loaded) to the Energy Dashboard as Battery Charge (IN) and Battery Usage (OUT). But it does not touched the battery at all.

Request to get besides the totals two dedicated sensors for the battery:

Battery input energy = Only in Charge Mode -> Input minus Output (this is what actually flows into the battery)
Battery output energy = Only in Battery Mode (Input OFF/0) -> Output (this is what actually flows out of the battery)

**Comment by vwt12eh8** [comment]
This problem has been resolved in [Ver.3](https://github.com/vwt12eh8/hassio-ecoflow/tree/ver3#readme). Please wait until release.

If you want to try now, please install pre-release version.
Note: Once you upgrade, you can't downgrade because it is not compatible with Ver.2.
