### ISSUE TITLE
DELTA Pro extra battery status changed

### ISSUE THREAD

**Issue by Jenda987** [vwt12eh8/hassio-ecoflow#7]
It looks like DELTA Pro extra battery status is changed each 6 seconds to unavailable and then in a half second (it's very quick) back to normal status.
Normal status
![obrazek](https://user-images.githubusercontent.com/22294702/178100629-62f6f3e5-a3fc-48cd-86b5-9ec60f04a1d6.png)
Unavailable status
![obrazek](https://user-images.githubusercontent.com/22294702/178100654-2f68bb41-7a33-42ec-b458-b7e125f2fa98.png)
Log
![obrazek](https://user-images.githubusercontent.com/22294702/178100821-045b2bd1-0512-45fa-968a-b71ff0ab6a11.png)
Everything else looks normal.
Remark - if firmware on extra battery wasn't updated then status was shown as 'Problem'. But maybe it's correct status.

**Comment by vwt12eh8** [comment]
Sorry. I fixed what I thought was a bug. 
If you can, please check #8 to see if it works.

**Comment by Jenda987** [comment]
I can confirm that DELTA Pro with extra battery it's working perfectly now. Thanks
