### ISSUE TITLE
Unknown Error Occurred when adding EcoFlow River Pro to HA

### ISSUE THREAD

**Issue by steviedeehook** [vwt12eh8/hassio-ecoflow#70]
Hi,
I downloaded hassio-ecoflow in HACS but when I try to add my device, after entering the IP address it does circles for a long time and then says and Unknown Error Occurred.
I know the Delta Pro had some issue with a port that needed to be open which seems to be resolved now.
I don't know if the problem I am having with the River Pro is related or not.
I can't see anything in the HA logs to give me a hit what the problem might be.
Any tips in troubleshooting would be greatly appreciated.
Ecoflow app says firmware is V1.2.5.17 V3.0.1.11(Wi-Fi)
Home Assistant 2023.2.5

**Comment by Leatherface75** [comment]
You need Wifi version v3.0.2.21 so that's your problem.

**Comment by steviedeehook** [comment]
Thank you. I hope Ecoflow update it soon!
