### ISSUE TITLE
Total Charge Level & Car Input unavailable with River Max

### ISSUE THREAD

**Issue by Leatherface75** [vwt12eh8/hassio-ecoflow#9]
Total Charge Level & Car Input unavailable with River Max

![image](https://user-images.githubusercontent.com/2489019/178109659-483b2ed4-f6b0-4fa6-8932-a2fb25e9edba.png)

Log says

> Logger: custom_components.ecoflow.ecoflow.rxtcp
> Source: components/number/__init__.py:175
> Integration: Ecoflow ([documentation](https://github.com/vwt12eh8/hassio-ecoflow), [issues](https://github.com/vwt12eh8/hassio-ecoflow/issues))
> First occurred: 16:15:49 (1 occurrences)
> Last logged: 16:15:49
> 
> 'MaxLevelEntity' object has no attribute '_attr_value'
> Traceback (most recent call last):
>   File "/config/custom_components/ecoflow/ecoflow/rxtcp.py", line 73, in __loop
>     self.received.on_next(data)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/subject/subject.py", line 59, in on_next
>     super().on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/observer.py", line 39, in on_next
>     self._on_next_core(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/subject/subject.py", line 66, in _on_next_core
>     observer.on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/config/custom_components/ecoflow/ecoflow/receive.py", line 42, in next
>     sub.on_next(x[:18 + size])
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/operators/_map.py", line 47, in on_next
>     obv.on_next(result)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/subject/subject.py", line 59, in on_next
>     super().on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/observer.py", line 39, in on_next
>     self._on_next_core(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/subject/subject.py", line 66, in _on_next_core
>     observer.on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/operators/_filter.py", line 38, in on_next
>     observer.on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/operators/_map.py", line 47, in on_next
>     obv.on_next(result)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/subject/subject.py", line 59, in on_next
>     super().on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/observer.py", line 39, in on_next
>     self._on_next_core(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/subject/replaysubject.py", line 106, in _on_next_core
>     cast(ScheduledObserver[_T], observer).ensure_active()
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/scheduledobserver.py", line 57, in ensure_active
>     self.disposable.disposable = self.scheduler.schedule(self.run)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/scheduler/trampolinescheduler.py", line 49, in schedule
>     return self.schedule_absolute(self.now, action, state=state)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/scheduler/trampolinescheduler.py", line 95, in schedule_absolute
>     self.get_trampoline().run(item)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/scheduler/trampoline.py", line 30, in run
>     self._run()
>   File "/usr/local/lib/python3.9/site-packages/reactivex/scheduler/trampoline.py", line 51, in _run
>     item.invoke()
>   File "/usr/local/lib/python3.9/site-packages/reactivex/scheduler/scheduleditem.py", line 27, in invoke
>     ret = self.scheduler.invoke_action(self.action, state=self.state)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/scheduler/scheduler.py", line 105, in invoke_action
>     ret = action(self, state)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/scheduledobserver.py", line 70, in run
>     work()
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/scheduledobserver.py", line 32, in action
>     self.observer.on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/usr/local/lib/python3.9/site-packages/reactivex/observer/autodetachobserver.py", line 28, in on_next
>     self._on_next(value)
>   File "/config/custom_components/ecoflow/__init__.py", line 244, in __updated
>     self.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
>     state = self._stringify_state(available)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
>     if (state := self.state) is None:
>   File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 170, in state
>     return self.value
>   File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 175, in value
>     return self._attr_value
> AttributeError: 'MaxLevelEntity' object has no attribute '_attr_value'

**Comment by vwt12eh8** [comment]
The specification of NumberEntity has been changed since Home Assistant 2022.7.

Please update to core-2022.7 or later to use this integration.

**Comment by Leatherface75** [comment]
Ok works now.
I was waiting with updating because i read about a lot of problems with various things.
